version: '3.8'

services:
  # Service de Reranking
  rerank-server:
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: rerank-server
    # Indispensable pour que le code Python puisse sortir vers Ollama sur un Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
    env_file:
      - ../../.env
    networks:
      - milvus-net 
    restart: unless-stopped
    command: uvicorn ingestor_server.rerank_service:app --host 0.0.0.0 --port 8001

  # Service RAG
  rag-server:
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: rag-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8004:8004"
    env_file:
      - ../../.env
    environment:
      # --- Communication vers le PREMIER compose ---
      - VDB_SERVICE_URL=http://vdb-server:8003
      - CHUNK_SERVICE_URL=http://chunk-service:8002
      
      # --- Communication vers Milvus (Réseau externe) ---
      - MILVUS_URI=http://milvus-standalone:19530
      
      # --- Communication INTERNE à ce compose ---
      - RERANK_URL=http://rerank-server:8001/rerank
      
      # --- Communication vers mon Mac ---
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - milvus-net
    restart: unless-stopped
    command: uvicorn ingestor_server.rag_service:app --host 0.0.0.0 --port 8004

networks:
  milvus-net:
    external: true
    name: milvus 