services:
  rerank-server:
    stop_grace_period: 1s
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: rerank-server
    # Indispensable pour que le code Python puisse sortir vers Ollama sur un Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8001"
    env_file:
      - ../../.env
    networks:
      - milvus-net 
    restart: unless-stopped
    command: uvicorn rerank_server.rerank_service:app --host 0.0.0.0 --port 8001


  rag-server:
    stop_grace_period: 1s
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: rag-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8004:8004"
    env_file:
      - ../../.env
    environment:
      - VDB_SERVICE_URL=http://vdb-server:8003
      - CHUNK_SERVICE_URL=http://chunk-service:8002
      - MILVUS_URI=http://milvus-standalone:19530
      - RERANK_URL=http://rerank-server:8001/rerank
      - OLLAMA_URL=http://host.docker.internal:11434
    networks:
      - milvus-net
    restart: unless-stopped
    command: uvicorn rag_server.rag_service_langfuse:app --host 0.0.0.0 --port 8004

networks:
  milvus-net:
    external: true
    name: milvus 