services:
  vdb-server:
    stop_grace_period: 1s
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: vdb-server
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "8003:8003"
    env_file:
      - ../../.env
    environment:
      # OVERWRITE : On pointe vers le container Milvus sur le réseau Docker
      - MILVUS_URI=http://milvus-standalone:19530
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - TOKENIZERS_PARALLELISM=false
    networks:
      - milvus-net
    restart: unless-stopped
    command: uvicorn ingestor_server.vdb_service.app_vdb_milvus:app --host 0.0.0.0 --port 8003


  chunk-service:
    stop_grace_period: 1s
    build:
      context: ../../
      dockerfile: deploy/compose/Dockerfile
    container_name: chunk-service
    extra_hosts:
    - "localhost:host-gateway"
    ports:
      - "8002:8002"
    env_file:
      - ../../.env
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4' # Augmente selon ton processeur 
    #       memory: 8G
    environment:
      # OVERWRITE : On pointe vers l'API VDB-Server qu'on vient de définir ci-dessus
      - VDB_SERVICE_URL=http://vdb-server:8003
      - TEI_ENDPOINT=http://embedding-ms:80
      # Chemin interne au container pour les modèles Docling
      - DOCLING_MODELS_PATH=/app/.cache/docling/models
      - HF_HOME=/app/.cache
      - TOKENIZERS_PARALLELISM=false
    volumes:
      # Montage du cache pour éviter de retélécharger les modèles Docling/HF
      - ~/.cache/docling/models:/app/.cache/docling/models
      - ~/.cache/huggingface:/app/.cache/huggingface
    networks:
      - milvus-net
    depends_on:
      - vdb-server
    restart: unless-stopped
    command: uvicorn ingestor_server.ingestor_service.app_chunks:app --host 0.0.0.0 --port 8002

networks:
  milvus-net:
    external: true
    name: milvus